/**********************************************************************
 *          Copyright (c) 1991 by Borland International, Inc.         *
**********************************************************************/

#define szAppName "SimplePaint"
#define LINE 1
#define ELLIPSE 2
#define RECTANGLE 3

#define MID_QUIT 100
#define MID_LINE 201
#define MID_ELLIPSE 202
#define MID_RECTANGLE 203
#define MID_THIN 301
#define MID_REGULAR 302
#define MID_THICK 303
#define MID_RED 304
#define MID_GREEN 305
#define MID_BLACK 306

