// Borland C++ - (C) Copyright 1991, 1992 by Borland International

// ffind.h

// string table definitions
#define IDS_NAME      1

// main dialog box defines
#define QX_1          101
#define QX_PATTERN    102
#define QX_2          103
#define QX_LIST       104
#define QX_COUNT      105
#define QX_3          106
#define QX_SEARCH     107
#define QX_CLEARW     108
#define QX_CANCEL     109

#define QX_DRV1       110
#define QX_DRV2       111
#define QX_DRV3       112
#define QX_DRV4       113
#define QX_DRV5       114
#define QX_DRV6       115
#define QX_DRV7       116
#define QX_DRV8       117
#define QX_DRV9       118

#define QX_ADDW       119
#define QX_NOREDRAW   120
#define QX_REDRAW     121

// dialog box resource id'S
#define MAIN          1

// end ffind.h

