// Borland C++ - (C) Copyright 1991, 1992 by Borland International

// hdump.h

// string table definitions
#define IDS_NAME      1

// menu defines
#define IDM_QUIT      101
#define IDM_ABOUT     102
#define IDM_OPEN      103
#define IDM_HOME      104

#define IDD_FNAME     16
#define IDD_FPATH     17
#define IDD_FLIST     18

// dialog box resource id'S
#define OPENFILE      1
#define ABOUT         2

// end hdump.h


