
/* Function Prototypes */

	int	    sbts_parser(char *, char *, int);
	void	    sbts_settings(int, int, int, int, int);
	void	    sbts_dict_ins(char *, char *);
	void	    sbts_init_dict();
	void	    sbts_dict_del(char *);
	long	    sbts_dict_dump(char *, char *);
	void	    sbts_say(char *);
	int	    sbts_init();
	void	    sbts_speakm(char *, int, int, int, int);
	void	    sbts_speakf(char *, int, int, int, int);
