
VidDrvHEADERs = c:\drv\gen.h c:\drv\pixel.hpp c:\drv\coord2d.hpp c:\drv\viddrive.hpp c:\drv\pal.h
VidDrvLIBs    = c:\drv\viddrv.lib

FontHEADERs   = c:\font\font.h c:\font\fontchr.h c:\font\textio.h c:\drv\bitmap.h

InputHEADERs  = c:\input\geninput.hpp c:\input\genclass.hpp c:\input\timer.hpp c:\input\gasclass.hpp
InputOBJs     = geninput.obj genclass.obj timer.obj gasclass.obj intsa.obj jsticka.obj jstickc.obj


